"""Initial migration

Revision ID: 6585dd4ef5e9
Revises: 6f273caa9836
Create Date: 2025-01-03 22:43:11.936168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6585dd4ef5e9'
down_revision: Union[str, None] = '6f273caa9836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('equipment_level', sa.String(), nullable=True),
    sa.Column('tools_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.create_index(op.f('ix_contractors_name'), 'contractors', ['name'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('construction_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_objects_id'), 'construction_objects', ['id'], unique=False)
    op.create_index(op.f('ix_construction_objects_name'), 'construction_objects', ['name'], unique=False)
    op.create_table('contractor_object_association',
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['construction_objects.id'], ),
    sa.PrimaryKeyConstraint('contractor_id', 'object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contractor_object_association')
    op.drop_index(op.f('ix_construction_objects_name'), table_name='construction_objects')
    op.drop_index(op.f('ix_construction_objects_id'), table_name='construction_objects')
    op.drop_table('construction_objects')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_contractors_name'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
