version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pg-db1
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: construction
    ports:
      - "8082:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    image: python:3.11-slim
    container_name: fastapi-app
    restart: always
    working_dir: /app
    volumes:
      - ./construction_api/app:/app
    command: >
        sh -c "pip install fastapi uvicorn sqlalchemy psycopg2-binary alembic && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql+pg8000://pguser:pwd123@localhost:8082/construction
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
